### ISSUE TITLE
Multiple pipelines are not working

### ISSUE THREAD

**Issue by FredrikNoren** [KiwiOrg/Kiwi#117]
Each pipeline seem to do work on all files

**Comment by philpax** [comment]
I changed the logic on Friday to accept one (no array) pipeline or many (array'd pipelines) per pipeline json, but if I'm understanding correctly, the issue is that all pipeline jsons apply to all files so it should be unrelated to my change.

**Comment by FredrikNoren** [comment]
Yeah exactly; the problem is that if you have multiple folders with a pipeline in each, they seem to be interfering
