### ISSUE TITLE
Build on stable Rust

### ISSUE THREAD

**Issue by philpax** [KiwiOrg/Kiwi#31]
At present, the runtime does not build on stable Rust. This is due to the use of four features:

```
#![feature(map_many_mut)]
#![feature(cursor_remaining)]
#![feature(coerce_unsized)]
#![feature(unsize)]
```

The first two features are primarily used for convenience and can be replaced with slightly-less-ergonomic equivalents. The latter two features are used to enable easy construction of `Cb` callback wrappers - it's likely that the downstream code will need to be changed to not rely on this, or another way is found to make `Cb` construction simpler.

**Comment by xunilrj** [comment]
I created a small commit to test how to remove `map_many_mut` at https://github.com/xunilrj/Kiwi/commit/b0c9b739c3cfef4b41755cbf7a7ac226ed121208.

Unfortunately, this solution has two issues:

1 - has unsafe;
2 - `rustc` is smart enough to complain that will cause conflicts in the future:

```
warning: an associated function with this name may be added to the standard library in the future
  --> crates/network/src/rpc.rs:65:60
   |
65 |         let [old_instance, new_instance] = state.instances.get_many_mut([&old_instance_id, &instance_id]).unwrap();
   |                                                            ^^^^^^^^^^^^
   |
   = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
   = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
   = help: call with fully qualified syntax `get_many_mut(...)` to keep using the current method
   = help: add `#![feature(map_many_mut)]` to the crate attributes to enable `HashMap::<K, V, S>::get_many_mut`
   = note: `#[warn(unstable_name_collisions)]` on by default
```

The worst part for me is that we need to use `*mut V` to bypass the borrow checker that complains about multiple `mut` borrows to the hashmap.

**Comment by pierd** [comment]
You could potentially use `hashbrown`'s `HashMap` directly in the meantime. That's what's used internally anyway so you'd basically bypass [the `map_many_mut` feature](https://github.com/rust-lang/rust/pull/94647).
