### ISSUE TITLE
Add raw Text/UI example

### ISSUE THREAD

**Issue by FredrikNoren** [KiwiOrg/Kiwi#35]
We can use the `text` component etc. to draw UI, even without a UI "framework" (like porting over the elements library)

**Comment by philpax** [comment]
Was looking at this briefly last night to see if we could get a score above the ball for @SK83RJOSH's golf. I think all we have to do is add primitive equivalents to the `text` components (using a system to translate them back)? It'd be really cool to have some 3D text as an example!
