### ISSUE TITLE
Model importer fails to cook collisions

### ISSUE THREAD

**Issue by SK83RJOSH** [KiwiOrg/Kiwi#48]
I imported a number of meshes from [Kenney NL](https://www.kenney.nl/assets/minigolf-kit) and close to half of them failed to cook:
```
[2023-02-12T17:38:01Z ERROR kiwi_model_import::model_crate] Failed to cook triangle mesh: Success
C:\Users\Josh\.cargo\git\checkouts\physx-rs-0df26257bd263938\92a09a9\physx-sys\PhysX/physx\source/physxcooking/src/mesh\TriangleMeshBuilder.cpp (1043) : internal error : cleaning the mesh failed
```
[examples.zip](https://github.com/KiwiOrg/Kiwi/files/10716771/examples.zip)

**Comment by SK83RJOSH** [comment]
A similar issue I noticed is that collisions don't appear to be very accurate, with things like small spheres being unable to pass through tunnels in objects such as this castle, and balls clipping through the bottom of things such as this platform (both attached).

[inaccurate_collisions.zip](https://github.com/KiwiOrg/Kiwi/files/10719579/inaccurate_collisions.zip)

**Comment by SK83RJOSH** [comment]
![image](https://user-images.githubusercontent.com/1371787/218538847-4c0935b8-dc7c-400f-b6ab-822e21201b1a.png)
Yeap, not sure what it is about these glbs in particular, but the generated collisions seem to mostly be inverted shells. No doubt whatever is causing this behavior is causing the failed baking.

**Comment by FredrikNoren** [comment]
@SK83RJOSH I added two flags to `FromMesh` in the pipeline; `flip_normals: false` and `reverse_indices: true`. Can you try if setting those help? reverse_indices might be a good place to start as it defaults to reversing.

Also you'll need to clear your cache each time anything changes with assets/pipeline (`tmp/http`).

**Comment by SK83RJOSH** [comment]
The results are perhaps a bit better, but still appears like there's some issues!

With `flip_normals` or `reverse_indices` set:
![image](https://user-images.githubusercontent.com/1371787/218725570-8b665598-82d0-4275-b094-3e026cccf5a0.png)

With both `flip_normals` and `reverse_indices` set:
![image](https://user-images.githubusercontent.com/1371787/218725804-98991197-c54f-4bd7-a6fc-5a854fb59c4c.png)

The second result seems pretty close to what I would consider a decent convex hull; but I expected this to use the triangular mesh instead of a convex mesh. 🙂

**Comment by SK83RJOSH** [comment]
With both `flip_normals` and `reverse_indices` set:
![image](https://user-images.githubusercontent.com/1371787/218727432-fc8c7463-46fa-4c33-89cf-c3c8566f3dfe.png)

Either or:
![image](https://user-images.githubusercontent.com/1371787/218728006-0785d9d5-f6bf-4dc7-8881-cdf270931a4e.png)

**Comment by FredrikNoren** [comment]
@SK83RJOSH So it's generating both a triangle mesh and a convex mesh. If the object is static it should use the triangle; if it's dynamic it should use the convex one. I could add an option to use convex meshes in the case of static too?

**Comment by SK83RJOSH** [comment]
> @SK83RJOSH So it's generating both a triangle mesh and a convex mesh. If the object is static it should use the triangle; if it's dynamic it should use the convex one. I could add an option to use convex meshes in the case of static too?

Might be wise to do this, but the core issue is resolved now at least :)

![image](https://user-images.githubusercontent.com/1371787/218857340-d5045171-d98d-474f-812e-62000c606a26.png)
