### ISSUE TITLE
Fix shadows and lighting in examples

### ISSUE THREAD

**Issue by FredrikNoren** [KiwiOrg/Kiwi#51]
Provide some kind of default lighting; right now everything looks flat because there's no "sun" entity set up.

**Comment by philpax** [comment]
Hah, @SK83RJOSH just ran into this. I was going to write an example on how to drive the sun - I might still do that as an interim solution.

**Comment by SK83RJOSH** [comment]
Yeah, I figured out how to create a sun, but it appears setting the rotation isn't affecting the shadow map at all:
`.with(rotation(), ...)` has no effect 🙂

**Comment by philpax** [comment]
Yeah, I'm not having much luck either: 

```rust
use kiwi_api::{
    components::core::{
        app::main_scene,
        camera::{active_camera, aspect_ratio_from_window, perspective_infinite_reverse},
        primitives::cube,
        rendering::{light_ambient, light_diffuse, sun},
        transform::{lookat_center, translation},
    },
    *,
};

#[main]
pub async fn main() -> EventResult {
    entity::game_object_base()
        .with_default(main_scene())
        .with(active_camera(), 0.)
        .with(translation(), vec3(5.0, 5.0, 4.0))
        .with(lookat_center(), vec3(0., 0., 0.))
        .with(perspective_infinite_reverse(), ())
        .with(aspect_ratio_from_window(), ())
        .spawn(false);

    let sun_uid = entity::game_object_base()
        .with_default(sun())
        .with(light_diffuse(), vec3(1., 0., 0.))
        .with(light_ambient(), vec3(1., 0., 0.))
        .spawn(false);

    let sun_id = entity::wait_for_spawn(&sun_uid).await;

    entity::game_object_base()
        .with_default(cube())
        .with(translation(), vec3(0., 0., 0.))
        .spawn(false);

    on(event::FRAME, move |_| {
        entity::set_rotation(sun_id, Quat::from_rotation_z(time()));

        EventOk
    });

    EventOk
}
```

I'd expect this to spin around the cube with red lighting, but I'm not seeing anything happen.

**Comment by SK83RJOSH** [comment]
I mistakenly added the sun to the camera object last night and noticed that the lighting updated (the faces facing the camera were fully lit) but the shadow map appeared to not update visibly. Might be useful information for triage; so adding it here (half-expecting this to be PEBKAC 😄)

**Comment by FredrikNoren** [comment]
There's also a `sun` example in the examples folder now
