### ISSUE TITLE
Expose a way to add assets to an object in the API

### ISSUE THREAD

**Issue by philpax** [KiwiOrg/Kiwi#68]
e.g.
```rust
Components::new()
  .set(model_from_url(), ...)
  .set(collider_from_url(), ...)
  .set(object_from_url(), ...)
```
The latter acts as a "template"; if that object is changed, all the components on the objects spawned from that template will be replaced with the new values from the template. This is most relevant to #12.

**Comment by philpax** [comment]
Can you set the collider from URL?

**Comment by FredrikNoren** [comment]
Yup; `collider_from_url`
